name: Test, build and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test_build_deploy:
    uses: Mentat-Software/cicd_playground/.github/workflows/build_test_deploy.yml@main
